### ISSUE TITLE
Catalog Ortelius Microservices into backstage for testing

### ISSUE THREAD

**Issue by bradmccoydev** [ortelius/backstage#153]
As we are building an integration for Ortelius to sit inside backstage. We need some test data. Lets catalog Ortelius microservices in there so that others can understand the hierarchy of components etc.

Simply copy and paste the Ortelius docs example in this file https://github.com/ortelius/backstage/blob/main/catalog-info.yaml and then you are away. make sure PR is merged and then backstage runs a scheduler to 'import' this component

Components look like this on a basic level:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ortelius-docs
  description: Ortelius Docs
  annotations:
    backstage.io/kubernetes-id: ortelius-docs
    github.com/project-slug: ortelius/ortelius-docs
    github.com/project-readme-path: README.md
  tags:
    - platform
  links:
    - url: https://docs.ortelius.io/
      title: Docs
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: production
```
